# Generated by Django 3.0.5 on 2020-04-08 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stagedoor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stagedoor_user_email",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stagedoor_user_phone_number",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
